# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LNtIPiWaYXZVLAGJYsOmJFV3erXxiwb2

###  The `app.py` Script

This script handles the data fetching, model training (or loading), and the interactive UI. I've switched the visualization to **Plotly** so users can hover over the prices to see exact values.
"""

import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

st.set_page_config(page_title="Crypto LSTM Predictor", layout="wide")

st.title("₿ Bitcoin Price Prediction Dashboard")
st.markdown("This app uses a **Long Short-Term Memory (LSTM)** neural network to predict BTC prices based on historical trends.")

# --- Sidebar Configuration ---
st.sidebar.header("User Input Parameters")
ticker = st.sidebar.selectbox("Select Asset", ["BTC-USD", "ETH-USD", "SOL-USD"])
start_date = st.sidebar.date_input("Start Date", value=pd.to_datetime("2020-01-01"))
end_date = st.sidebar.date_input("End Date", value=pd.to_datetime("today"))
window_size = st.sidebar.slider("Prediction Window (Days)", 30, 90, 60)

# --- Data Loading ---
@st.cache_data
def load_data(symbol, start, end):
    data = yf.download(symbol, start=start, end=end)
    return data

data = load_data(ticker, start_date, end_date)
st.subheader(f"Historical Data for {ticker}")
st.line_chart(data['Close'])

# --- Preprocessing & Model Training ---
if st.button("Train Model & Predict"):
    with st.spinner("Processing sequences and training LSTM..."):
        # Prepare Data
        close_prices = data[['Close']].values
        scaler = MinMaxScaler(feature_range=(0, 1))
        scaled_data = scaler.fit_transform(close_prices)

        train_len = int(len(scaled_data) * 0.8)
        train_data = scaled_data[:train_len]

        X_train, y_train = [], []
        for i in range(window_size, len(train_data)):
            X_train.append(train_data[i-window_size:i, 0])
            y_train.append(train_data[i, 0])

        X_train, y_train = np.array(X_train), np.array(y_train)
        X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))

        # Define Model
        model = Sequential([
            LSTM(50, return_sequences=True, input_shape=(X_train.shape[1], 1)),
            Dropout(0.2),
            LSTM(50, return_sequences=False),
            Dropout(0.2),
            Dense(1)
        ])
        model.compile(optimizer='adam', loss='mean_squared_error')
        model.fit(X_train, y_train, batch_size=32, epochs=5, verbose=0)

        # Testing
        test_inputs = scaled_data[train_len - window_size:]
        X_test, y_test = [], close_prices[train_len:]
        for i in range(window_size, len(test_inputs)):
            X_test.append(test_inputs[i-window_size:i, 0])

        X_test = np.array(X_test)
        X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))

        # Predictions
        preds = model.predict(X_test)
        preds = scaler.inverse_transform(preds)

        # --- Plotly Visualization ---
        st.subheader("Prediction Results")
        fig = go.Figure()
        fig.add_trace(go.Scatter(x=data.index[train_len:], y=y_test.flatten(), name="Actual Price", line=dict(color='white')))
        fig.add_trace(go.Scatter(x=data.index[train_len:], y=preds.flatten(), name="LSTM Prediction", line=dict(color='orange')))

        fig.update_layout(template="plotly_dark", xaxis_title="Date", yaxis_title="Price (USD)")
        st.plotly_chart(fig, use_container_width=True)

        st.success("Model trained successfully! Note: This is for educational purposes only.")